"""New migration

Revision ID: 5483fb9c7f6d
Revises: a44846e1d157
Create Date: 2025-02-13 23:26:04.508252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5483fb9c7f6d'
down_revision = 'a44846e1d157'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
